[package]
authors = ["Rafael Lemos <contact@flemosr.com"]
name = "collect-envoy-protos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
glob = "0.3.1"
tonic-build = { version = "0.9.2", features = ["prost"] }
