[package]
authors = ["Rafael Lemos <contact@flemosr.com"]
name = "envoy-proto-collect"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "collect-protos"
path = "src/main.rs"

[dependencies]
glob = "0.3.1"
