[package]
authors = ["Rafael Lemos <contact@flemosr.com"]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "authorization-server"
path = "src/authorization_server.rs"

[dependencies]
envoy-types = { path = "../envoy-types" }
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
tonic = "0.9.2"
